### ISSUE TITLE
Doesn't work with Flickr

### ISSUE THREAD

**Issue by natevw** [aaronpk/IndieAuth.com#1]
I changed my Flickr URL to point to my profile instead of my photos, and I still hit the case where it didn't think my login matches the actual_username of "Nathan Vander Wilt": https://github.com/aaronpk/IndieAuth/blob/master/controller.rb#L184

I don't am not a Rails expert and don't see any fixtures that contain the actual Flickr config data, so it's hard to guess what attempted_username it's trying to match against — perhaps "natevw" versus "Nathan Vander Wilt"?

**Comment by sebilasse** [comment]
seeAlso the providers json in: https://github.com/aaronpk/IndieAuth.com/issues/88
