### ISSUE TITLE
Link without href causes the parser to break

### ISSUE THREAD

**Issue by jeena** [aaronpk/IndieAuth.com#103]
So we just had someone using this valid HTML:

```
<span class="fn"><a rel="me" class="u-url">Tyson VanOverhill</a></span>
```

which caused the IndieAuth to crash and not even recognice the rel=me links which come afterwards, see screenshot.

![iaerr](https://cloud.githubusercontent.com/assets/151764/8469071/93e82812-2029-11e5-838d-b89523f079b7.png)

**Comment by aaronpk** [comment]
This has been fixed with the addition of relative URL resolution in 285cb2906a92960ae38140e04b9f60c899bbb01f
