### ISSUE TITLE
request to distributed indieauth service needs state

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#104]
The `state` parameter is missing when trying to use `indiecert.net` with `indieauth.com`.

**Comment by fkooman** [comment]
Is there a reason why there is no state parameter? Is there no risk of CSRF here? If so I can just remove the state requirement from indiecert.net.

**Comment by aaronpk** [comment]
What's the actual problem here? Is indieauth.com not passing the state parameter back when it should be? It's a little unclear whether your summary is describing the problem or the solution.

**Comment by fkooman** [comment]
Ah, following OAuth 2.0 RFC, the use of the `state` parameter in the "authorization request" is recommended, to avoid CSRF.

**Comment by aaronpk** [comment]
Right, it's not part of the token exchange, but it's both a way to avoid CSRF as well as a way to allow a client to associate a request after the user returns with the initial request. This is a common use since the callback URL has to be unique, state is the only thing that can vary between requests.

**Comment by fkooman** [comment]
And it seems indieauth.com does not do that when redirecting to distributed indieauth providers...

**Comment by aaronpk** [comment]
Okay. Can you provide an example of the steps I can do to reproduce the failure?

**Comment by fkooman** [comment]
1. go to https://indieauth.com
2. type https://www.tuxed.net/ as domain 
3. choose indiecert.net as the provider from the list
4. see there is no state provided in the error message and URL bar

**Comment by aaronpk** [comment]
Thanks. I'll work on this soon.

**Comment by fkooman** [comment]
Thanks!

**Comment by sebilasse** [comment]
related to https://github.com/aaronpk/IndieAuth.com/issues/85
