### ISSUE TITLE
Twitter rel-me-discovery failing

### ISSUE THREAD

**Issue by kylewm** [aaronpk/IndieAuth.com#108]
When I rescan my auth providers I get the error message
```
 twitter.com/kylewmahan
No rel=me link was found on https://twitter.com/kylewmahan to https://kylewm.com/
```

@adactio said he and multiple other people at HWC in Brighton were seeing the same issue today.

**Comment by aaronpk** [comment]
Twitter seems to have updated the list of user agents they're redirecting to the mobile website, and the mobile website doesn't have the rel=me attribute. This should be fixed in b20812553984311a61d740548d8c5b7e1e608e90
