### ISSUE TITLE
Replace Persona

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/IndieAuth.com#110]
Persona will be shut down by the end of 2016, so we'll need another solution for email verification with indieauth.com

Ideally I would like to support both emailing a login link (or a verification code), as well as autodetecting the email provider and using their OAuth/OpenID provider. This is the way Poetica handles email logins currently.

<img width="613" alt="poetica-email-login" src="https://cloud.githubusercontent.com/assets/113001/12406822/9db00d90-be05-11e5-8f03-9e1156e13d56.png">

**Comment by sknebel** [comment]
From discussions around the shutdown of Persona on HN and Reddit an effort to build something new similar to it emerged, meeting in #letsauth on freenode and with some info on github: https://github.com/letsauth/letsauth.github.io/wiki. Might be worth tracking what they are doing.
