### ISSUE TITLE
state isn't quoted properly in embedded JS

### ISSUE THREAD

**Issue by snarfed** [aaronpk/IndieAuth.com#113]
indieauth's JS crashes when i send it a `state` param with double quotes inside. i think you want to escape double quotes on [this line](https://github.com/aaronpk/IndieAuth.com/blob/3799eb95d126c7670b5c847236ce0ae894b4769b/views/auth.erb#L5):

```js
var state = "<%= @state %>";
```

thanks in advance!

**Comment by snarfed** [comment]
i fixed this on my end by url-encoding my state param, which i arguably should have been doing in the first place. :P up to you if you still want to do anything about this or just close as wontfix!

**Comment by aaronpk** [comment]
Interesting point. You definitely need to URL-encode the state parameter anyway, since it gets passed around mostly in the URL. That said, I should fix this anyway because you could use this bug to inject malicious JS right now by crafting a state value such as `"; alert("hello"); "`
