### ISSUE TITLE
Fails when trying to log into Düsseldorf wiki page?

### ISSUE THREAD

**Issue by voxpelli** [aaronpk/IndieAuth.com#115]
When I'm logged out on the IndieWebCamp wiki and try to log in from https://indiewebcamp.com/2016/D%C3%BCsseldorf/Guest_List, then I repeatedly get an error. If I on the other hand log in from eg. the front page of the wiki, then everything is fine.

The error is: `An unhandled lowlevel error occured. The application logs may have details.`

I assume that the `ü`-character in `Düsseldorf` is what causes the error.

**Comment by voxpelli** [comment]
Perhaps of interest that I'm trying to log in using `kodfabrik.se` and the GitHub connection.

**Comment by aaronpk** [comment]
Yes, it looks like it's failing when it's building the redirect URI, since the URL has non-ascii chars in it.

```
URI::InvalidURIError - URI must be ascii only
```

**Comment by aaronpk** [comment]
Thanks, fixed in 2a5c231ddb8e9b8106a09812bf43432e34a335cb
