### ISSUE TITLE
Google+ profile no longer adds rel="me" to links

### ISSUE THREAD

**Issue by cvn** [aaronpk/IndieAuth.com#116]
As a result, I wasn't able to use G+ with indieauth.

I think this is part of the recent G+ redesign, discussed here: https://googleblog.blogspot.com/2015/11/introducing-new-google.html

<img width="420" src="https://cloud.githubusercontent.com/assets/774864/15103279/45d78c46-155e-11e6-9d53-7a97c7841544.png">

**Comment by aaronpk** [comment]
Closing since Google+ shut down 😂
