### ISSUE TITLE
Can't login to MediaWiki OpenID plugin

### ISSUE THREAD

**Issue by singpolyma** [aaronpk/IndieAuth.com#122]
On http://faow.referata.com/ I just get

> Verification of the OpenID URL failed. Error message: "Server denied check_authentication" 

When using my domain which is delegated to openid.indieauth.com/openid

**Comment by strk** [comment]
It doesn't look like faow.referata.com has an openid login anymore, is this ticket any useful ?

**Comment by aaronpk** [comment]
I'm going to close this since the site doesn't appear to have OpenID support anymore.
