### ISSUE TITLE
Allow different resulting user URL after login

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/IndieAuth.com#123]
Should support the auth endpoint returning a different URL after logging in, must be on the same domain

**Comment by cweiske** [comment]
Test link: https://indieauth.com/auth?me=https://commentpara.de/&client_id=https%3A%2F%2Findieauth.com&redirect_uri=https%3A%2F%2Findieauth.com%2Fsuccess

**Comment by aaronpk** [comment]
thanks for the example!
