### ISSUE TITLE
sms verification failing

### ISSUE THREAD

**Issue by singpolyma** [aaronpk/IndieAuth.com#127]
`curl -i 'https://primary.indieauth.com/auth/verify_sms.json?...snip...`

`TypeError: no implicit conversion of nil into String`

**Comment by joelpurra** [comment]
In a possibly related issue, the error response seems to be missing `Access-Control-Allow-Origin`.

> XMLHttpRequest cannot load `https://primary.indieauth.com/auth/verify_sms.json?...` No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin `https://indieauth.com` is therefore not allowed access. The response had HTTP status code 500.

This might affect the user experience. In my case the browser stays in the "Verifying..." mode for that phone number, without any further explanation (for users who don't use the browser console) nor visible verification timeout UI result.

**Comment by jwds1978** [comment]
I'm noticing the same as @joelpurra . I receive the verification message on my phone, but after entering the code on the Web site to complete verification, it stays stuck at "Verifying...".

**Comment by aaronpk** [comment]
As of today, I've removed SMS support, since SMS is not secure. More details here: https://aaronparecki.com/2017/03/11/22/day-81-indieauth
