### ISSUE TITLE
Current state of providers

### ISSUE THREAD

**Issue by sebilasse** [aaronpk/IndieAuth.com#130]
While doing the node.js work, I stumbled upon the providers in https://github.com/aaronpk/IndieAuth.com/blob/master/models/provider.rb

_-1, might be removed:_
- beeminder : There seems to be no `rel="me"` links at all on the possible pages

_0, note:_
- eventbrite and
- google : There seems to be no `rel="me"` links in _new_ profiles, seeAlso https://github.com/aaronpk/IndieAuth.com/issues/116
  Might be mentioned in the docs but should remain, plenty of old g+-profiles supporting it …

_+1, might be supported:_
- flickr works for me, seeAlso https://github.com/aaronpk/IndieAuth.com/issues/1 – the regex in JS would be like `'https?:\/\/(?:www[.])?flickr[.]com[/]*(?:people[/]*)?([^/]+)'` (although using URI templates with JS)

[checked allOf https://github.com/glennjones/elsewhere-mapper/blob/master/lib/mapdata.json] :
- **stackexchange** supports both `rel="me"` links and OAuth2, see :
  http://stackexchange.com/users/991329/sebastian-lasse
  https://api.stackexchange.com/docs/authentication

I am also checking which providers would allow to change your url directly, e.g.
twitter POST /account/update_profile ['url']
github PATCH /user ['blog']

**Comment by sebilasse** [comment]
@aaronpk 
Please note also that indieauth-node will have working support for
• flickr 
• profiles within stackexchange (e.g. stackoverflow etc.)
• google+ profiles :
  `https://plus.google.com{/userId}/about/?gmbpt=true&fd=2` but fetch it with
  `User-Agent: curl/7.51.0`
• youtube
• instagram
  currently sandbox, app must be reviewed by instagram

**Comment by sebilasse** [comment]
The google stuff is no longer true 3 days (!) later:

> It also means it’s time to say goodbye to classic Google+ on the web, which we’ll be turning down on January 24.

**Comment by dg01d** [comment]
Is there anything to be said for a method of providing Known Instances as an identity provider?

**Comment by sebilasse** [comment]
@dg01d Not sure. But I'd be very interested in this question. So please allow me to ping @benwerd @benmedium regarding `withknown` above ...

**Comment by aaronpk** [comment]
Known already supports the IndieAuth protocol, so if you are signing in as your Known site you don't need to also authenticate with a third party. If you wanted to use Known as your authorization endpoint from some other website, we'd have to figure out something else, because Known will reject an authorization attempt for a profile URL that isn't its own.

![screenshot 2017-03-31 06 57 50](https://cloud.githubusercontent.com/assets/113001/24553552/693973d4-15df-11e7-870f-6d251b2e405a.png)
