### ISSUE TITLE
Wrong link in indieauth.com "Join Us"

### ISSUE THREAD

**Issue by sebilasse** [aaronpk/IndieAuth.com#131]
minor issue:
The "guest list" link in the "Join Us" section no more redirects to the last Guest List but to 2014:
https://indieweb.org/Guest_List redirects to 2014/UK/ - 
the link is mentioned in the indieauth.com "Join Us" section …

**Comment by julianfoad** [comment]
I see no "guest list" link in the "Join Us" section. Perhaps it's been removed to fix this issue?

**Comment by aaronpk** [comment]
Yes, this was removed in ef5c0da9b92a515a1b30dd0292b933edccbecf1c
