### ISSUE TITLE
Using `//twitter.com/***` link errors out

### ISSUE THREAD

**Issue by html5cat** [aaronpk/IndieAuth.com#135]
I'm using Medium.com custom domains at `http://dybskiy.com` and getting error trying to login.
Seems like url that medium is using is `//twitter.com/html5cat`

**Comment by aaronpk** [comment]
Good catch

**Comment by html5cat** [comment]
I believe @benwerd fixed it on medium side, but would be nice to have it fixed here just in case too?

**Comment by sebilasse** [comment]
@html5cat Just curious - wanna have this in the indieauth-node clone fixed as well :
What exactly is the error. One question: https and http URLs are considered to be different, so have you tried to change the URL linking from twitter to http://dybskiy.com to https://dybskiy.com ?

**Comment by aaronpk** [comment]
The problem is (was?) that medium was linking to the Twitter URL as a protocol relative link, literally `//twitter.com/html5cat`. The solution is to make sure to resolve all URLs based on the URL of the page fetched.

**Comment by sebilasse** [comment]
Ah, I see - makes perfectly sense.
