### ISSUE TITLE
GPG login is not mentioned on the Setup page

### ISSUE THREAD

**Issue by sebilasse** [aaronpk/IndieAuth.com#137]
https://indieauth.com/setup
does not mention 
"How To login with GPG" -
a link to https://indieauth.com/gpg would do the trick ;)

And for newer versions of GPG Tools for OS X :
It will Sign the Selection to a new window by default but you can activate the "plain" `Sign` command in the Services Settings ...

**Comment by aaronpk** [comment]
This is done, thanks!
