### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/IndieAuth.com#138]
This should not be named the same thing as the spec. This confuses people into thinking that the spec somehow relies on the indieauth.com service.

**Comment by aaronpk** [comment]
Feel free to bikeshed name ideas here. I think following the [p3k naming convention](https://indieweb.org/p3k_naming_convention) would be fun but I'm open to other ideas as well.

**Comment by dg01d** [comment]
Avion?

Utterly bonkers bat-wing aircraft designed by Clément Ader in the 1890s.
See: [Wikipedia Avion III](https://en.wikipedia.org/wiki/Ader_Avion_III)

**Comment by ojn** [comment]
Signmark, org and io domains are available.

**Comment by dissolve** [comment]
aviato? :trollface:

**Comment by kevinmarks** [comment]
Would "visiting card" be the victorian thing?

**Comment by kevinmarks** [comment]
Or the great seal https://en.m.wikipedia.org/wiki/Great_Seal_of_the_Realm

**Comment by cweiske** [comment]
identproxy

**Comment by aaronpk** [comment]
> identproxy

or... proxident, tho that kind of sounds like toothpaste

**Comment by cweiske** [comment]
proxident extra white professional

**Comment by voxpelli** [comment]
identity.plumbing

**Comment by kevinmarks** [comment]
Escutcheon

**Comment by dissolve** [comment]
Indentity?
IndieAccess
BikeshedID

**Comment by sknebel** [comment]
logthem.in? (for sites delegating)
ownyourauth?
auththemall? (why does the mall need to be authed?)

**Comment by rhiaro** [comment]
IndieAuth As A Service, IAAAS, prounounced "YAAAASSSS!!!"

**Comment by tantek** [comment]
Since the service is user-facing, it deserves a more user-friendly name than IndieAuth or anything else plumbingy / jargony.

**Comment by mblaney** [comment]
it's going to be hard to top IAAAS, but I suggested signet on IRC a while ago.... sort of feels like it has a steam punk vibe :-)

**Comment by sebilasse** [comment]
`indieauth.rocks` would indicate it is a tool, but maybe particularly a "validator" 
`logthem.in` seems to be available - [check](https://registry.in/whois/logthem.in)
`iauth.me` seems to be available - [check here](http://whois.nic.me)

**Comment by sebsel** [comment]
someauth, short for 'social media auth', but also 'this auth is sooo me'~

**Comment by jjuran** [comment]
indielogin.{com,net,org} are all available.

**Comment by petermolnar** [comment]
following the p3k scheme: sigil?

**Comment by kevinmarks** [comment]
It's authentication, so call it "it me"

**Comment by aaronpk** [comment]
Did I mention I actually need two names for this? 😂 

* The service that users delegate their domain to (analogous to how choosing an OpenID provider used to be a thing, e.g. myopenid.com). This is used for authorization as well as authentication.
* The service for developers that abstracts RelMeAuth, that allows users to sign in with their domain. Authentication only.

**Comment by kevinmarks** [comment]
Definitely ”itme" and "icanhaz" then 😎

**Comment by aaronpk** [comment]
Currently considering:

* **glassmark[.net]** for users
* **nymix[.io]** for developers

So, the question is, would you sign up for a service called **glassmark**? e.g. would you switch from myopenid.com to glassmark[.net]?

If you're building an app, would you direct your users to **nymix[.io]** to sign in? This is also what people signing in to the indieweb.org wiki will be redirected to when signing in.

Now I'm going to let these sit for a while and come back later and see if I still think they're a good idea.

**Comment by cweiske** [comment]
Something handling my identity has *glass* in its name .. bad idea.

**Comment by sebilasse** [comment]
totally agreed to cweiske - misleading for german speakers, so

>  would you switch from myopenid.com to glassmark[.net] ?

No. Additionally it would leave me freaked out.
about (1) Like @kevinmarks idea having `me` in it 

Why must the service for developers also be renamed - whats wrong with `IndieAuth` ?

**Comment by aaronpk** [comment]
Okay, did not realize that "glass" had such a strong connotation for Germans!

The service for developers is something that their users will see. I realized that they will also need to give instructions to their users to add the rel=me links to their websites, or point their users at the docs on this site: https://indieauth.com/setup

For this reason, the name of the developers' service actually needs to be even more user-friendly than the other one, because with IndieAuth the authorization server, you'll only see that site if you "sign up" for it by linking to the authorization endpoint.

The developers' service is also only used for *login* (authentication), not authorization. For this reason, I'm now leaning towards "indielogin" as the name. This means the docs on indielogin will never mention the word "auth" or "authorization".

**Comment by aaronpk** [comment]
I just registered indielogin.com

**Comment by aaronpk** [comment]
Closing this as the new names have been decided. Thanks for the input everyone!
