### ISSUE TITLE
IndieAuth.com authenticator does not use openid2 metadata

### ISSUE THREAD

**Issue by strk** [aaronpk/IndieAuth.com#144]
I already advertise my OpenID-2.0 provider from my website (http://strk.kbt.io) but when I try to login on indieauth.com I'm told I need to add "me" links with email or pgp key as the only ways to control my own authentication (rather than delegate to github/twitter/whatever).

This ticket is to request that OpenID-2.0 is also supported for authentication.

\cc @aaronpk

**Comment by strk** [comment]
I dunno if installing http://indieauth.id.cweiske.de/ would be enough to add that support. 
\cc @cweiske

**Comment by aaronpk** [comment]
Closing because this would now be a request for https://indielogin.com and I don't plan on adding OpenID support to the other replacement service for this one.
