### ISSUE TITLE
rescan button missing after changing authorization endpoint

### ISSUE THREAD

**Issue by cweiske** [aaronpk/IndieAuth.com#146]
Screenshot: http://fotostore.cweiske.de/screenshots/2017-04-21%20indieauth%20no%20rescan.png

I did the following:

1. Use indieauth.com to login with cweiske.de
2. I only have no rel-me and one authorization_endpoint
3. Successfull authenticated
4. Change authorization_endpoint on cweiske.de
5. Try to login on indieauth.com
6. Error: 

> There was a problem!
> "http://cweiske.de/indieauth-openid-0.1.0.phar/" was not found on the site "http://cweiske.de/". Try re-scanning after checking your rel=me links on your site.

**Comment by sebsel** [comment]
This happened again, see https://chat.indieweb.org/wordpress/2017-09-18#t1505715005147000

Would be nice to add a `[re-scan]` button to this view:

![schermafbeelding 2017-09-18 om 09 33 04](https://user-images.githubusercontent.com/16517999/30532640-a9abcf64-9c55-11e7-88b8-3e8de00875f0.jpg)

**Comment by aaronpk** [comment]
Thanks. I should add a button to this view that deletes the cached info so that starting over will find the new endpoint.

**Comment by aaronpk** [comment]
This is fixed. I made the site delete the cache automatically if it encounters this error. I've updated the error message as well.
