### ISSUE TITLE
Unable to sign in with my (SNI) SSL site

### ISSUE THREAD

**Issue by barryf** [aaronpk/IndieAuth.com#148]
I'm no longer able to use IndieAuth.com to log in with my site (https://barryfrost.com). 

When trying to fetch my rels, I'm getting:
> Unknown error retrieving https://barryfrost.com/: too many connection resets (due to SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: tlsv1 alert internal error - OpenSSL::SSL::SSLError)

I can fetch with a local version of IndieAuth.com, but not on your server. I use Heroku's SNI service so this leads me to think it may be related to #78: perhaps your version of Ruby and/or OpenSSL has changed?

**Comment by aaronpk** [comment]
Nothing has changed on the server recently. I just tested fetching your site manually and it worked fine. Maybe this was a transient error? Can you check if it's working now?

**Comment by barryf** [comment]
No change unfortunately:

https://barryf.s3.amazonaws.com/barryfrost-indieauth.png

**Comment by aaronpk** [comment]
huh, well I have no explanation for this, but I restarted the app and now it finds your site.

**Comment by barryf** [comment]
I'm still seeing this: sometimes it works but mostly not. But it seems isolated to my server for whatever reason so rather than clog up your issues I'll close this and focus my efforts on building an indieauth/token endpoint. Good excuse to build one.

**Comment by aaronpk** [comment]
Based on https://github.com/sparklemotion/mechanize/issues/123, I just tried adding `keep_alive=false` to the code. Let me know if this improves things.

**Comment by barryf** [comment]
Yes, that's helped, thanks! Failure rate is down to about 50% but I can now log in to the IndieWeb wiki.
