### ISSUE TITLE
Error with relative rel="authorization_endpoint" URLs

### ISSUE THREAD

**Issue by sknebel** [aaronpk/IndieAuth.com#152]
On my site, I had (as the only provider)
```html
<link href="/auth" rel="authorization_endpoint">
``` 
IndieAuth.com then tried to redirect me to /auth -> which, being a relative link, lead me to https://indieauth.com/auth *again*, causing a redirect loop (or, once changed to `/auth2`, a 404 from Indieauth.com) The URL is not properly normalized to be relative to the page it is in. 
(To be clear, this is the case where it is the only auth source and IndieAuth.com immediately redirects, I haven't checked what happens when multiple options are present and it is choosen in the UI)

https://github.com/aaronpk/IndieAuth.com/blob/36cc779a8aeeed8d848676ba8768eb8869cd7c58/lib/relparser.rb#L167 Looks like a possible location for a fix.

**Comment by sebsel** [comment]
Wanted to file this one, but Sknebel already has. Encountered this too with `<link rel="authorization_endpoint" href="/selfauth/" />` in my `<head>`, but without the looping redirect ofcourse ;) so +1
