### ISSUE TITLE
Email auth returns HTTP 504, can't be used

### ISSUE THREAD

**Issue by joelpurra** [aaronpk/IndieAuth.com#158]
When attempting to authenticate via email, clicking the `my.name@example.com` button displays the text "Sending verification code..." and then nothing happens in the UI.

Looking at the browser console, it seems `/auth/send_email.json?me=...` returns HTTP 504. The verification code actually arrives via email a few minutes later, but as the input field is never shown in the UI the process cannot be completed.

**Comment by joelpurra** [comment]
Just noting that the problem persists, preventing me from using indieauth as an openid provider.

**Comment by aaronpk** [comment]
I just tried this with your account and it worked fine (sorry for the extra email you just got). Can you provide any more details about the conditions in which this fails?

**Comment by joelpurra** [comment]
I did receive the email from your authentication attempt. Can't verify the email timing compared to your UI experience, but did you see the verification code input box after clicking?

**Comment by joelpurra** [comment]
Testing authenticating using the email buttons just now still returns a 504 after 60 seconds.

- Using indieauth through openid to log in to one of the stackexchange sites.
- Already logged in to at least one of them "sometime last month," which worked.
- The browser is Vivaldi
- While I do have adblocking extensions, it seems to be a server issue as hinted by the 504 status code.
- I think that #161 hints at server problems as well (and guessing it's not my server which responds sub-second).

**Comment by aaronpk** [comment]
I did see the verification code box after I sent that email. Let's keep this discussion in https://github.com/aaronpk/IndieAuth.com/issues/161#issuecomment-318113958 since I'm now 99.9% sure they are all related.
