### ISSUE TITLE
Github auth returns HTTP 504, can't be used

### ISSUE THREAD

**Issue by joelpurra** [aaronpk/IndieAuth.com#161]
Clicking the github button to authenticate using indieauth (as an openid provider) does not work. Instead I see a 504 Gateway Time-out message.

See also #158 which returns 504 for email authentication.

**Comment by aaronpk** [comment]
I'm suspicious that all the issues you filed are related to timeout errors fetching your site. Where is your site hosted?

**Comment by aaronpk** [comment]
I'm looking into this some more to track down the source of the error. The commonality is the server timing out trying to verify things on your site, which is why I am thinking they are all related.

**Comment by joelpurra** [comment]
Assuming that my website (hosted in the north of Sweden) is not the problem as the front page loads "fast" (from Germany) -- definitely not near the 504 timings (60 seconds or more?) I've seen.

```bash
time curl --silent 'https://joelpurra.com/' >/dev/null
```
```text
real	0m0.673s
user	0m0.073s
sys	0m0.022s
```

See https://joelpurra.com/

**Comment by aaronpk** [comment]
I tried running `ab` (apache bench) on your site and got some interesting results. From my other server, it has no problems completing 50 requests with a concurrency of 10 in just a few seconds. But from the server that hosts indieauth.com, I get a flood of `SSL read failed (5) - closing connection` errors. 

Probably the biggest difference between these two servers is that the indieauth.com has an IPv6 address and your site also advertises an IPv6 address. Just for fun, I disabled the IPv6 address on the server and tested with `ab` again and it worked fine! So it appears there's something wrong over the IPv6 connection between these two servers!

Do you know if you've set up IPv6 properly on your end? I'm not actually sure it's set up right on mine so I might just keep it disabled for now.

**Comment by joelpurra** [comment]
@aaronpk: great find! I do have IPv6 enabled, and while I can't test it from my current network (ISP is on IPv4) I'll see what I can find.

**Comment by joelpurra** [comment]
@aaronpk: sorry to have bothered you. Just got word that one of the transits used by my web host has had problems with IPv6 for at least the past three days. Might also have been the issue one week ago as well, when I initially tried to use indieauth.

As my ISP is on IPv4 I probably wouldn't have figured it out without your help. Sorry that you ended up disabling IPv6 while testing. As authentication worked with my IPv6-enabled domain before, I assume the setup on your end is working.
