### ISSUE TITLE
Twitter and github authentication methods disappearing

### ISSUE THREAD

**Issue by joelpurra** [aaronpk/IndieAuth.com#163]
After the very, very slow update (several minutes) happened in #162, the authentication methods for github and twitter have disappeared. After the first run twitter disappeared, and after the second run github also disappeared.

**Comment by joelpurra** [comment]
Quite possibly related to IPv6 problems en route to my server. Expect my web host to fix it asap. See #161.

**Comment by aaronpk** [comment]
Yep, this is definitely related. On future requests, the server will show only the providers that it's been able to verify. Since we were seeing timeout errors, sometimes one provider would get through and show up, and then the next time it'd time out and it would remove it from the list.
