### ISSUE TITLE
Add support for security keys (U2F)

### ISSUE THREAD

**Issue by joelpurra** [aaronpk/IndieAuth.com#168]
I've been using a security key from Yubikey as 2FA for my google account for a few years now. Works great! A recent post by @agl reminded me that the same security keys can be used on other sites too. There is a standard called FIDO U2F, to be superseded by W3C Web Authentication, which enables this.

Perhaps something for indieauth.com?

- https://twitter.com/agl__/status/898219500134252544
- https://www.imperialviolet.org/2017/08/13/securitykeys.html
- https://www.w3.org/TR/webauthn/
- https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-u2f-javascript-api.html
- https://security.googleblog.com/2017/02/better-and-more-usable-protection-from.html
- https://security.googleblog.com/2014/10/strengthening-2-step-verification-with.html

**Comment by joelpurra** [comment]
Enticing images:

[![Screenshot of Google's U2F 2FA screen, by Google](https://2.bp.blogspot.com/-n-YPPXRj4XM/Vd3d3CkBmNI/AAAAAAAAAHA/t6VaBUZHEJs/s1600/Screen%2BShot%2B2014-09-28%2Bat%2B11.15.24%2BPM%2B%25281%2529.png)](https://security.googleblog.com/2014/10/strengthening-2-step-verification-with.html)

[!["YubiKey NEO works over both USB-A and NFC", by Yubikey](https://www.yubico.com/wp-content/uploads/2015/11/YubiKey-NEO-phone-laptop-1030x687.png)](https://www.yubico.com/press/images/)

**Comment by aaronpk** [comment]
I definitely want to support this! However, it only makes sense when the user has a pre-existing relationship with the service, as it requires pre-registration of the key. This means it can't be part of the generic RelMeAuth abstraction, and instead can only be used when the user delegates their domain to this service. 

If you haven't heard, I'm planning on splitting indieauth.com into two new domains and eventually deprecating indieauth.com. More info on that here https://github.com/aaronpk/IndieAuth.com/milestones

I'm going to close this issue as a duplicate of #141 and copy the links you provided into that issue. Thanks!
