### ISSUE TITLE
ID page generated by AngularJS app doesn't work

### ISSUE THREAD

**Issue by aswathrao** [aaronpk/IndieAuth.com#181]
When the ID page is dynamically generated by AngularJS app, IndieAuth server is not able to extract the relevant rel="me" lines. I kind of know why this is happening. For example, if I click "view page source" menu item, Chrome does not display all the lines in the Head section. But if I click "Inspect" menu item and expand Head section under Elements, then I see all the rel=?me" lines.  Any suggestion on how to handle this? You can use http://app.enthinnai.s3-website-us-east-1.amazonaws.com/#/id/aswath23 as an example page. TIA

**Comment by aaronpk** [comment]
You will need to make sure the links are rendered server-side and served in the HTML. You can at the very least add `<link>` tags to your base Angular template that serves up the Javascript app. I have no plans on adding JS rendering to IndieAuth.com.

**Comment by aswathrao** [comment]
Thanks for the suggestion. I will pass it on to the developer.
