### ISSUE TITLE
Warning on array param

### ISSUE THREAD

**Issue by boricensis** [aaronpk/IndieAuth.com#183]
From my log:

[Fri Nov 16 06:50:54.668419 2018] [:error] [pid 27488] [client 50.68.53.12:51422] PHP Warning: **array_search() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/indieauth/includes/class-indieauth-authorization-endpoint.php on line 230**, referer: https://itheorist.com/wp-login.php?redirect_to=https%3A%2F%2Findielogin.com%2[....]

**Comment by aaronpk** [comment]
This is a bug with the WordPress IndieAuth plugin, can you file the issue here? https://github.com/indieweb/wordpress-indieauth/issues
