### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by alienlebarge** [aaronpk/IndieAuth.com#184]
Hi,

I'm currently trying to sign in with IndieAuth. But I have some problems ...

The first time I tried, I was able [to register](https://indieauth.com/setup). But now it does not work anymore.
I always got the following error:
```
Error retrieving: http://alienlebarge.ch
```
![capture d ecran 2019-02-01 a 15 36 09](https://user-images.githubusercontent.com/611234/52129153-1c380180-2637-11e9-8cb7-ded71ac57a4a.png)

Is there something I've done wrong ?
Thanks for your help 😄

**Comment by aaronpk** [comment]
There seem to be DNS errors with your domain. I've seen this happen before with misconfigured DNSSEC. I'm not getting any DNS results for the domain when querying.

**Comment by alienlebarge** [comment]
Thanks for the answer.

Now, it seems to work. (I haven't touch anything)

Perhaps something about the DNS propagation. I was fine tunning it some hours ago.
