### ISSUE TITLE
Consider using RSA-based signatures for tokens

### ISSUE THREAD

**Issue by jamietanna** [aaronpk/IndieAuth.com#193]
Currently, the format of the tokens provided by IndieAuth.com is a signed JWT (JWS) using HS256.

If we were to update this to be RS256, we could allow clients to treat it as a JWS, not an opaque token that needs to be introspected by the token endpoint.

This could allow clients validating tokens as such to do so much more easily, locally, while reducing load on the token endpoint.

Because token revocation is not widespread at this point, it would enable clients to not need to introspect unnecessarily.

**Comment by jamietanna** [comment]
Per [comments on chat](https://chat.indieweb.org/dev/2020-03-18#bottom) - not yet

**Comment by aaronpk** [comment]
There's an OAuth 2.0 extension describing a JWT profile for access tokens https://oauth.net/2/jwt-access-tokens/ 

But actually indieauth.com doesn't make any access tokens itself, that's handled by a separate project: https://github.com/aaronpk/IndieAuth-Token-Endpoint 

Also the eventual goal is to replace both of these with a new project that more cleanly implements these ideas, and using JWT access tokens according to that spec is a good idea for that new work.

**Comment by jamietanna** [comment]
That's fair - didn't realise it was a different repo - want me to raise an issue on that repo to cover it?
