### ISSUE TITLE
Bridging IndieAuth → OpenID supported?

### ISSUE THREAD

**Issue by JuliusPC** [aaronpk/IndieAuth.com#200]
I tried to use IndieAuth.com as bridge to authenticate at a OpenID ([yes, it is OpenID, not OpenID Connect](https://dashboard.uberspace.de/login?from_beta=1&lang=en)) enabled service ([uberspace](https://uberspace.de)) with my own selfauth instance. _After_ successful authentication my browser was redirected to indieauth.com instead of uberspace.

I am not sure whether this is a bug or this crude flow is simply not supported.

**Comment by aaronpk** [comment]
It should work, I tried logging in with mine and I was taken back to uberspace.de

**Comment by heyarne** [comment]
I can confirm that this works. I have my website setup to use PGP / Github auth and can login to uberspace no problem (after #206 has been fixed).
