### ISSUE TITLE
Invalid `redirect_uri` causes a 500, which the user is not informed of

### ISSUE THREAD

**Issue by jamietanna** [aaronpk/IndieAuth.com#202]
When trying to, accidentally, use an invalid `redirect_uri`, the application returns a 500, when really this should be a 400.

In some flows (i.e. via GitHub login) a generic error is returned to the user.

When signing in with email, the verification API call returns a 500, and the UI is stuck at `Verifying...` forever.

Example invalid URL:

```
https://indieauth.com/auth?redirect_uri=localhost%3A8080&client_id=https%3A%2F%2Fwww-editor.jvt.me&state=state&scope=create+update+delete+undelete+media&response_type=code&me=https://www.jvt.me
```

**Comment by aaronpk** [comment]
This is fixed in 795f01119754f51de22ddd3ef795daf038905792 which now shows a better error message to the user
