### ISSUE TITLE
"The redirect_uri must be a valid URL."

### ISSUE THREAD

**Issue by heyarne** [aaronpk/IndieAuth.com#206]
Following the changes of 795f011 I can't login with IndieAuth via OpenID anymore. The page I'm trying to login to is https://dashboard.uberspace.de/login?from_beta=1&lang=en, the `redirect_uri` is "/openid/complete". This worked perfectly before.

I can manually enter the client and redirect_uri to both contain the domain, is this required by the spec or is this an overly strict interpretation? Thanks for running this service and providing the OpenID integration, it has proven immensely useful to me!

**Comment by heyarne** [comment]
Thanks for the quick response! Unfortunately I get another error now:
> Missing OpenID session data

**Comment by aaronpk** [comment]
Sorry about that! I used the wrong config variable. Try again!

**Comment by heyarne** [comment]
Yes, great! Thanks a lot. :)
