### ISSUE TITLE
Support IndieAuth-enabled individual websites

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/IndieAuth.com#53]
See http://indiewebcamp.com/login-brainstorming for more details

If the user signing in has included an `authorization_endpoint` link then the IndieAuth client should be able to offer that as an option in addition to any common OAuth providers found.

**Comment by andyleap** [comment]
What's the status on this?  I just implemented IndieAuthProtocol on my site only to find it's next to useless as most sites rely on indieauth.com

**Comment by aaronpk** [comment]
wow I can't believe it's been almost a year that this has been open. I will get to this soon, but note that all the micropub clients do IndieAuth on their own and don't use indieauth.com, so at least you can try signing in to those.

**Comment by andyleap** [comment]
I've tested and confirmed that my implementation is working, all the way up to publishing from Quill(Yay!, such nice UI).
