### ISSUE TITLE
Provide WebID strategy to omniauth to create an IndieAuth provider.

### ISSUE THREAD

**Issue by almereyda** [aaronpk/IndieAuth.com#61]
For me it is important to be able to use own infrastructures within the (distributed/federated - *choose yourself*) web. As I see a little controversy [as seen in the WebFinger Mailing List](https://groups.google.com/d/msg/webfinger/461mLR1sQ00/iKmXokO-CjoJ) between W3C and IndieWeb efforts, being the choice of strategical or practical approaches, 

[`omniauth` needs a WebID strategy](https://github.com/intridea/omniauth/wiki/List-of-Strategies), but they don't even have [an issue](https://github.com/intridea/omniauth/issues) for that yet.

@bblfish and @elf-pavlik , could you give me some hints on how to move into the integration of WebID and IndieAuth, therefore allowing some kind of *four-point-five linkedopendata stars* interactions?

> How do you assure long-term interoperability and accessibility in the same time? Or will federation just mean, that we all talk many languages (=protocols)?

Maybe, to give a glimpse of the response I will have to give back to the WebFinger's, the fact of coming and going standards might just mean we'll have to do the plumbing all the times, until mature standards emerge that stay (like HTML, TCP/IP, etc.).

**Comment by aaronpk** [comment]
I don't want to go down the route of adding cert-based providers to indieauth.com. There is already https://indiecert.net which is an IndieAuth-compatible authorization server that supports client certs. Someone could also write an IndieAuth-compatible server that authenticates people via WebID. Check out http://indiewebcamp.com/distributed-indieauth for details on implementing a server.

**Comment by elf-pavlik** [comment]
seeAlso: https://github.com/fkooman/indiecert/issues/6
