### ISSUE TITLE
Add client certificate authentication provider

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/IndieAuth.com#77]
...so that users can authenticate from a client cert in their browser

**Comment by elf-pavlik** [comment]
@aaronpk see @kooman's https://indiecert.net/welcome | https://github.com/fkooman/indiecert

**Comment by aaronpk** [comment]
indiecert.net is a great implementation of this, so I'm going to leave it out of indieauth.com

**Comment by elf-pavlik** [comment]
I added it to https://indiewebcamp.com/IndieAuth#Details
