### ISSUE TITLE
state parameter required on verify POST

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#81]
It looks like the `state` parameter is needed in POST requests to the `auth` endpoint on IndieAuth.com. Is this actually really required in order for IndieAuth to be safe?

**Comment by fkooman** [comment]
My client lib just sends the `state` parameter now, IndieCert just ignores it...

**Comment by aaronpk** [comment]
The state parameter is used to prevent CSRF attacks. See http://tools.ietf.org/html/rfc6749#section-10.12 for more details. By requiring the state parameter is sent to the authorization endpoint when verifying auth codes, it acts as a built-in check that the client used it.
