### ISSUE TITLE
normalize 'me'

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#82]
In case multiple similar looking URLs all point to the same 'effective' URL the final URL should be used after following redirects etc. This is to avoid confusing by creating different accounts for basically the same URL.

For example my domain is `tuxed.net`. If one specifies `tuxed.net` IndieAuth should append `https://`. If a URL starts with `http://` or is otherwise malformed it should be rejected.

The URL should be fetched and all redirects should be followed (enforcing strict HTTPS only redirects).

In the case of `tuxed.net` it would be rewritten as `https://tuxed.net` and then fetched. It will redirect to `https://www.tuxed.net/` and then onwards to `https://www.tuxed.net/fkooman/`.

So the effective URL and the one that should be used for identifying the user should be `https://www.tuxed.net/fkooman/`. 

So if next time I type `https://www.tuxed.net` or `tuxed.net/fkooman` it will all resolve to the same URL and no confusion will happen with different URLs mapping to different accounts.

**Comment by evert** [comment]
The fact that there's a redirect on that url does not imply that the canonical url should become the target of the redirect. I do think it would be good that the URL normalization rules should be applied.

**Comment by aaronpk** [comment]
Actually this is not the correct behavior. Currently IndieAuth.com already follows redirects in what I believe is the correct way. Basically whatever the user types in should be treated as canonical. For more background, see this thread: https://github.com/aaronpk/IndieAuth.com/issues/19

**Comment by aaronpk** [comment]
Sorry, I shouldn't have closed this. I do think that if you enter a bare domain, it should be normalized to a full URL with https. So entering `fkooman.net` would result in the identity `https://fkooman.net/` being used everywhere.

**Comment by fkooman** [comment]
Ah that seems like an acceptable compromise :-)

What about support for subdomains and folders though? What should happen if I type `www.tuxed.net`? What happens if I type `tuxed.net/fkooman`? Will those be normalized to `https://www.tuxed.net/` and `https://tuxed.net/fkooman/`? Or a `/` is only added to hostname (it is impossible to know if `fkooman` in this case is a file or folder...so it needs to be fetched first...)? 

Maybe it should be enforced that only a (valid) hostname can be specified as a 'me' parameter?

**Comment by elf-pavlik** [comment]
You could set identity to the URI which dereferenced (HTTP GET) returns the web page with rel="me" & rel="authorization_endpoint"

Except if it has rel="canonical", with URI which belongs to redirect path leading to this retrieved document (one with rel="me") (to cover cases like #19, which IMO shouldn't use HTTP 301!)

I use as my canonical web page https://wwelves.org/perpetual-tripper/ (while having as my identity URI https://wwelves.org/perpetual-tripper which 303 redirects to =+ '/', to respect address [httpRange-14](http://en.wikipedia.org/wiki/HTTPRange-14) resulution)

I also see no reason why not to use for example shortened version for easy typing e.g. *tiny.cc/elf* 

```bash
$ curl -I https://tiny.cc/elf
HTTP/1.1 301 Moved Permanently
Location: https://wwelves.org/perpetual-tripper/
```
Which would follow redirect and than use my web page URI as my identity: https://wwelves.org/perpetual-tripper/

**Comment by aaronpk** [comment]
@elf-pavlik see the example in #19 where he intended on using "dreev.es" as his identity, but "dreev.es" is actually a 301 redirect to his university page. Whatever you enter in the IndieAuth domain prompt is going to be the identity. I do not think it makes sense for the system to use a different identity than what you entered based on redirects.

@fkooman `https://tuxed.net/fkooman` and `https://tuxed.net/fkooman/` are two completely different URLs and there is no way to automatically map between them. If you send a 301 redirect from one to the other then things will work fine. `https://tuxed.net` is not a complete URL since there is no path component, so it is acceptable to add a slash making it `https://tuxed.net/`.

**Comment by elf-pavlik** [comment]
IMO dreev.es should have used something else than 301 *permanent* e.g. 303 *other*
also http://ai.eecs.umich.edu/people/dreeves/ should include

```<link rel="canonical" href="http://dreev.es/" />```

If you ignore redirects, typing *http://wwelves.org/perpetual-tripper* will use that as identity URI, even that after 2 redirects you get response from *https://wwelves.org/perpetual-tripper/* ?

**Comment by fkooman** [comment]
Elf and I were discussing the `http://dreev.es` use case and thought it may not be a very common thing to do. Indie{Auth,Cert} requires a `https://` URL anyway, and if your provider already installs a certificate for your domain then you can (and should?) also trust them with your data. So I think this particular use case does no longer exist in the `https://` scenario. 

Whether or not that makes the URL follower scenario and using the actual URL that returns `200` as the user identity a good idea is still open for debate I guess, but issue #19 is not really relevant any more :)

Also:
```
$ curl https://dreev.es/
curl: (7) Failed to connect to dreev.es port 443: Connection refused
$ 
```
```
$ curl https://ai.eecs.umich.edu/people/dreeves
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
$
```

**Comment by aaronpk** [comment]
I also thought it was not going to be a common case at all, but then he showed up with it, and since he was one of the first couple hundred people to sign in, I'd say that's a pretty high overall probability of it happening again.

I'll close this issue and re-open a new one for the trailing slash and auto-https issue.
