### ISSUE TITLE
support Accept header on auth endpoint for verification using POST

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#83]
Especially `application/json` :)

**Comment by fkooman** [comment]
My client lib will now send the Accept header for `application/json` but still work when a `application/x-www-form-urlencoded` response comes back...

**Comment by aaronpk** [comment]
More context for the change here: http://aaronparecki.com/articles/2015/03/05/1/re-proposed-changes-to-indieauth-protocol##Content+negotiation
