### ISSUE TITLE
Normalize user-entered "me" URL

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/IndieAuth.com#84]
If the user enters a bare domain, normalize it to "https://example.com/"

If the user enters a domian with no tailing slash, add a slash so "https://example.com" becomes "https://example.com/"

**Comment by evert** [comment]
There's a few more normalization rules aside from the optional trailing slash. All of the following URIs should ideally be treated as identical:

1. `https://example.org/%7Eevert`
2. `https://example.org/%7eevert`
3. `https://example.org/~evert`
4. `https://example.org/./~evert`
5. `https://example.org:/~evert`
6. `https://example.org:443/~evert`
7. `HTTPS://EXAMPLE.ORG/~evert`

If it's not the case already. The normalization rules for HTTP and generic URIs can be found in:

* http://tools.ietf.org/html/rfc7230#section-2.7.3
* http://tools.ietf.org/html/rfc3986#section-6

**Comment by elf-pavlik** [comment]
This doesn't cover my and @fkooman's use cases

* https://tuxed.net/fkooman
* https://tuxed.net/fkooman/
* https://www.tuxed.net/fkooman
* https://www.tuxed.net/fkooman/

and

* http://wwelves.org/perpetual-tripper
* http://wwelves.org/perpetual-tripper/


To my understanding currently IndieAuth will create 4 different identities for @fkooman and 2 different ones for me. Depending if we manually have entered following / or not (and www subdomain)

Both versions without slash redirect to / in our cases

```shell
$ curl -IL https://tuxed.net/fkooman
HTTP/1.1 301 Moved Permanently
Location: https://www.tuxed.net/fkooman

HTTP/1.1 301 Moved Permanently
Location: https://www.tuxed.net/fkooman/
```

```shell
$ curl -I https://wwelves.org/perpetual-tripper --insecure
HTTP/1.1 303 See Other
Location: http://wwelves.org/perpetual-tripper/
```
moving to new VM and will fix my cert...

**Comment by fkooman** [comment]
Implemented aaronpk's suggestion in IndieCert.

**Comment by kylewm** [comment]
IndieAuth currently normalizes by [removing the trailing slash](https://github.com/aaronpk/IndieAuth.com/blob/master/controllers/auth-web.rb#L63) rather than adding one. So it's a little bit unfortunate that adding the slash (though correct) will break consumers who have saved the user's identity as e.g., "https://kylewm.com".

**Comment by elf-pavlik** [comment]
> In general, a URI that uses the generic syntax for authority with an
   empty path should be normalized to a path of "/".

https://tools.ietf.org/html/rfc3986#section-6.2.3

**Comment by kylewm** [comment]
> @kylewm i see that you refer to particular implementation choice of indieauth.com not the IndieAuth as protocol/spec

Yes absolutely. Updated to .com, sorry for the confusion.
