### ISSUE TITLE
do not send `me` to callback

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#85]
It is not needed to send `me` to the callback URL of a relying party. The relying party MUST keep state anyway and can bind the initially user provided normalized `me` (see #84) to that particular state for matching against the `me` response in the verify POST.

**Comment by sebilasse** [comment]
Same here !

**Comment by aaronpk** [comment]
Yep this is absolutely correct. Consumers SHOULD be using the `state` parameter, which means they either maintain a session or encode data into the parameter to avoid needing a session. I can't immediately deprecate this on the live indieauth.com, but when I re-launch the new service as a developer tool I can avoid including the parameter in the response to begin with. I will assign it to the appropriate milestone.

**Comment by aaronpk** [comment]
It's going to take a while to deprecate this parameter since many clients are still expecting it. We should track down as many Micropub clients as we can and open issues like this on all of them: https://github.com/aaronpk/Quill/issues/79
