### ISSUE TITLE
"tuxed.net" does not work as identity

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#86]
1. Go to `https://indieauth.com/`
2. Use `tuxed.net` as identity
3. Re-Scan
4. `"There was an SSL error connecting to https://www.tuxed.net/fkooman/"`

Without Re-Scan it doesn't work if you choose the cached values, by either choosing Twitter or GitHub:`Unknown error retrieving http://tuxed.net:`

Also using `https://tuxed.net/` or the effective URL `https://www.tuxed.net/fkooman/` does not work: `Unknown error retrieving https://www.tuxed.net/fkooman:`

cURL example on `https://tuxed.net/`:

```
[fkooman@franet ~]$ curl -LI https://tuxed.net/
HTTP/1.1 301 Moved Permanently
Date: Sat, 21 Mar 2015 08:14:14 GMT
Server: Apache/2.2.15 (CentOS)
Location: https://www.tuxed.net/
Connection: close
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 302 Moved Temporarily
Date: Sat, 21 Mar 2015 08:14:15 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.6.6
Location: https://www.tuxed.net/fkooman/
Connection: close
Content-Type: text/html; charset=UTF-8

HTTP/1.1 200 OK
Date: Sat, 21 Mar 2015 08:14:15 GMT
Server: Apache/2.2.15 (CentOS)
Vary: Host
Last-Modified: Sun, 15 Mar 2015 17:54:33 GMT
ETag: "14812c9-7d9-511576d17cee6"
Accept-Ranges: bytes
Content-Length: 2009
Connection: close
Content-Type: text/html
```

cURL on `https://www.tuxed.net/fkooman/`:

```
[fkooman@franet ~]$ curl -LI https://www.tuxed.net/fkooman/
HTTP/1.1 200 OK
Date: Sat, 21 Mar 2015 08:14:43 GMT
Server: Apache/2.2.15 (CentOS)
Vary: Host
Last-Modified: Sun, 15 Mar 2015 17:54:33 GMT
ETag: "14812c9-7d9-511576d17cee6"
Accept-Ranges: bytes
Content-Length: 2009
Connection: close
Content-Type: text/html

[fkooman@franet ~]$ 
```

**Comment by aaronpk** [comment]
I believe this has been fixed since upgrading the root certs. Correct @fkooman?

**Comment by fkooman** [comment]
Hmm... I didn't get any of these errors anymore no, so I guess it is fixed :)
