### ISSUE TITLE
400 status response is expected, not wrong

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#93]
The `HEAD` request to `https://indiecert.net/auth` returns a 400, as expected, because the required parameters are missing.

See https://tools.ietf.org/html/rfc6749#section-5.2

![indieauth_indiecert net](https://cloud.githubusercontent.com/assets/616885/7909872/f55fe838-084f-11e5-938e-9f52bc022080.png)

**Comment by aaronpk** [comment]
You're right, that should accept an HTTP 400 status code.

**Comment by aaronpk** [comment]
To fix this, I need to figure out how to make the Mechanize gem treat HTTP 400s as a success, rather than raising an exception for them.

**Comment by fkooman** [comment]
This particular issue seems fixed, still doesn't work due to missing state in the request, but I'll open another issue for that :)

**Comment by fkooman** [comment]
Hm... it worked once and now is not working again after trying to login to IndieWebCamp wiki?

**Comment by fkooman** [comment]
Another solution: just send the correct parameters, you already know them anyway :-)

**Comment by singpolyma** [comment]
I'd like to use indiecert.net, but this issue is blocking me for now

**Comment by fkooman** [comment]
I solved this particular issue by just returning a 200 OK on a HEAD request to the auth endpoint. At least it gets one step further now.

**Comment by aaronpk** [comment]
Sorry that took so long. This is fixed now! IndieAuth.com will now also look for the `IndieAuth` header even if the response code is HTTP 400.
