### ISSUE TITLE
implement introspection for resource servers e.g. micropub endpoints

### ISSUE THREAD

**Issue by fkooman** [aaronpk/IndieAuth.com#96]
See: https://tools.ietf.org/html/draft-richer-oauth-introspection

For example, it can then be used here: http://indiewebcamp.com/auth-brainstorming#Verifying_access_tokens

A verification request would look like this then (from the micropub service to IndieAuth):
```
$ curl \
    -H "Authorization: Bearer <out of band registered secret between micropub endpoint and IndieAuth>" \
    -d "token=<token to verify>" \
    https://tokens.indieauth.com/introspect
```

JWT is not always an option to avoid introspection because then you cannot revoke access tokens, they will need to expire...

**Comment by aaronpk** [comment]
As you noted in the example above, this is done by the token endpoint, not indieauth.com. Here's the issue for implementing the introspection draft: https://github.com/aaronpk/IndieAuth-Token-Endpoint/issues/3

Note that the token endpoint already does support introspection, but using the parameter names that were used during authorization, not the ietf draft: https://tokens.indieauth.com/#verify
